name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
    paths-ignore:
        - '**.md'
        - 'docs/**'
        - 'LICENSE'
        - '.gitignore'
        - '.dockerignore'
        - '**.env'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Zig and cargo-zigbuild
        run: |
          wget https://ziglang.org/download/0.16.0/zig-x86_64-linux-0.16.0.tar.xz
          tar -xf zig-linux-x86_64-0.16.0.tar.xz
          sudo cp -r zig-linux-x86_64-0.16.0/* /usr/local/bin/
          cargo install cargo-zigbuild

      - name: Build for AMD64
        run: cargo zigbuild --release --target x86_64-unknown-linux-gnu

      - name: Build for ARM64
        run: cargo zigbuild --release --target aarch64-unknown-linux-gnu

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=short

            type=raw,value=edge,enable=${{ github.ref == 'refs/heads/main' }}
      
      - name: Build and push AMD64 image
        uses: docker/build-push-action@v7
        with:
          context: .
          build-args: BINARY_PATH=target/x86_64-unknown-linux-gnu/release/reminder-bot
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v7
        with:
          context: .
          build-args: BINARY_PATH=target/aarch64-unknown-linux-gnu/release/reminder-bot
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


